const fs = require('fs');

const missingQuestions = [
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τον ακόλουθο πίνακα με τον αριθμό πρωτονίων (p), νετρονίων (n) και ηλεκτρονίων (e) για κάθε σωματίδιο:<br><br><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Όνομα στοιχείου</th><th>Βρώμιο<br>\\(^{80}_{35}\\text{Br}\\)</th><th>Μαγγάνιο<br>\\(^{55}_{25}\\text{Mn}\\)</th><th>Φωσφόρος<br>\\(^{31}_{15}\\text{P}\\)</th><th>Κάλιο<br>\\(^{39}_{19}\\text{K}\\)</th><th>Υδρογόνο<br>\\(^{1}_{1}\\text{H}\\)</th><th>Σίδηρος<br>\\(^{56}_{26}\\text{Fe}^{3+}\\)</th><th>Θείο<br>\\(^{32}_{16}\\text{S}^{2-}\\)</th><th>Φθόριο<br>\\(^{19}_{9}\\text{F}^{-}\\)</th><th>Νάτριο<br>\\(^{23}_{11}\\text{Na}^{+}\\)</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2 font-bold'>Αριθμός p</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2 font-bold'>Αριθμός n</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2 font-bold'>Αριθμός e</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>",
    a: "<span class='text-purple-300 font-bold'><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Όνομα στοιχείου</th><th>Βρώμιο</th><th>Μαγγάνιο</th><th>Φωσφόρος</th><th>Κάλιο</th><th>Υδρογόνο</th><th>Σίδηρος (ιόν)</th><th>Θείο (ιόν)</th><th>Φθόριο (ιόν)</th><th>Νάτριο (ιόν)</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2 font-bold'>Αριθμός p</td><td>35</td><td>25</td><td>15</td><td>19</td><td>1</td><td>26</td><td>16</td><td>9</td><td>11</td></tr><tr class='border-b border-white/10'><td class='text-left py-2 font-bold'>Αριθμός n</td><td>45</td><td>30</td><td>16</td><td>20</td><td>0</td><td>30</td><td>16</td><td>10</td><td>12</td></tr><tr class='border-b border-white/10'><td class='text-left py-2 font-bold'>Αριθμός e</td><td>35</td><td>25</td><td>15</td><td>19</td><td>1</td><td>23</td><td>18</td><td>10</td><td>10</td></tr></tbody></table></span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να μελετήσετε τον αριθμό πρωτονίων, νετρονίων και ηλεκτρονίων των X, Ψ, Z, Ω και να χαρακτηρίσετε το καθένα στη τελευταία στήλη του πίνακα: ουδέτερο άτομο, κατιόν (+), ή ανιόν (-).<br><br><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th></th><th>Αριθμός p</th><th>Αριθμός n</th><th>Αριθμός e</th><th>Χαρακτηρισμός</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='font-bold'>X</td><td>13</td><td>14</td><td>10</td><td></td></tr><tr class='border-b border-white/10'><td class='font-bold'>Ψ</td><td>16</td><td>16</td><td>18</td><td></td></tr><tr class='border-b border-white/10'><td class='font-bold'>Z</td><td>19</td><td>20</td><td>19</td><td></td></tr><tr class='border-b border-white/10'><td class='font-bold'>Ω</td><td>56</td><td>81</td><td>54</td><td></td></tr></tbody></table>",
    a: "<span class='text-purple-300 font-bold'><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th></th><th>Αριθμός p</th><th>Αριθμός n</th><th>Αριθμός e</th><th>Χαρακτηρισμός</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='font-bold'>X</td><td>13</td><td>14</td><td>10</td><td>Κατιόν (+3)</td></tr><tr class='border-b border-white/10'><td class='font-bold'>Ψ</td><td>16</td><td>16</td><td>18</td><td>Ανιόν (-2)</td></tr><tr class='border-b border-white/10'><td class='font-bold'>Z</td><td>19</td><td>20</td><td>19</td><td>Ουδέτερο (άτομο)</td></tr><tr class='border-b border-white/10'><td class='font-bold'>Ω</td><td>56</td><td>81</td><td>54</td><td>Κατιόν (+2)</td></tr></tbody></table></span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τον παρακάτω πίνακα με τα στοιχεία που λείπουν:<br><br><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Στοιχείο / Ιόν</th><th>Σύμβολο</th><th>Z</th><th>A</th><th>e</th><th>p</th><th>n</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2'>Κάλιο</td><td>K</td><td>19</td><td>39</td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Ιώδιο</td><td>I</td><td></td><td>127</td><td>53</td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Υδράργυρος</td><td>Hg</td><td>80</td><td></td><td></td><td></td><td>122</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Βισμούθιο</td><td>Bi</td><td>83</td><td>209</td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Ιόν ασβεστίου</td><td>Ca²⁺</td><td>20</td><td>40</td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Ιόν χλωρίου</td><td>Cl⁻</td><td>17</td><td>37</td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Νέο</td><td>Ne</td><td>10</td><td></td><td></td><td></td><td>10</td></tr></tbody></table>",
    a: "<span class='text-purple-300 font-bold'><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Στοιχείο / Ιόν</th><th>Σύμβολο</th><th>Z</th><th>A</th><th>e</th><th>p</th><th>n</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2'>Κάλιο</td><td>K</td><td>19</td><td>39</td><td>19</td><td>19</td><td>20</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Ιώδιο</td><td>I</td><td>53</td><td>127</td><td>53</td><td>53</td><td>74</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Υδράργυρος</td><td>Hg</td><td>80</td><td>202</td><td>80</td><td>80</td><td>122</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Βισμούθιο</td><td>Bi</td><td>83</td><td>209</td><td>83</td><td>83</td><td>126</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Ιόν ασβεστίου</td><td>Ca²⁺</td><td>20</td><td>40</td><td>18</td><td>20</td><td>20</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Ιόν χλωρίου</td><td>Cl⁻</td><td>17</td><td>37</td><td>18</td><td>17</td><td>20</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Νέο</td><td>Ne</td><td>10</td><td>20</td><td>10</td><td>10</td><td>10</td></tr></tbody></table></span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τα κενά στο παρακάτω κείμενο:\\n\\nΤα ηλεκτρόνια τοποθετούνται σε στιβάδες, ξεκινώντας από τη στιβάδα ________ προς τις στιβάδες ________ ενέργειας. Η στιβάδα ________ ενέργειας για όλα τα άτομα είναι αυτή που βρίσκεται πιο ________ στον πυρήνα, δηλαδή η ________. Οι στιβάδες συμπληρώνονται με έναν αριθμό ηλεκτρονίων που δίνεται από τον τύπο: ________, όπου n είναι ο αριθμός της στιβάδας.",
    a: "<span class='text-purple-300 font-bold'>Τα ηλεκτρόνια τοποθετούνται σε στιβάδες, ξεκινώντας από τη στιβάδα (Κ) προς τις στιβάδες υψηλότερης ενέργειας. Η στιβάδα χαμηλότερης ενέργειας για όλα τα άτομα είναι αυτή που βρίσκεται πιο κοντά στον πυρήνα, δηλαδή η (Κ). Οι στιβάδες συμπληρώνονται με έναν αριθμό ηλεκτρονίων που δίνεται από τον τύπο: 2n², όπου n είναι ο αριθμός της στιβάδας.</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τα κενά στο παρακάτω κείμενο:\\n\\nΤο άτομο του χλωρίου έχει ατομικό αριθμό 17 και μαζικό 35, επομένως στον πυρήνα έχει ________ πρωτόνια και ________ νετρόνια και γύρω από τον πυρήνα σε στιβάδες, με βάση το πρότυπο Bohr, κινούνται ________ ηλεκτρόνια. Η κατανομή των ηλεκτρονίων σε στιβάδες είναι: ________. Το χλώριο ________ ένα ηλεκτρόνιο και σχηματίζει το ________ Cl⁻ που έχει κατανομή ηλεκτρονίων σε στιβάδες: ________.",
    a: "<span class='text-purple-300 font-bold'>Το άτομο του χλωρίου έχει ατομικό αριθμό 17 και μαζικό 35, επομένως στον πυρήνα έχει 17 πρωτόνια και 18 νετρόνια και γύρω από τον πυρήνα σε στιβάδες, με βάση το πρότυπο Bohr, κινούνται 17 ηλεκτρόνια. Η κατανομή των ηλεκτρονίων σε στιβάδες είναι: K(2)-L(8)-M(7). Το χλώριο προσλαμβάνει ένα ηλεκτρόνιο και σχηματίζει το ανιόν Cl⁻ που έχει κατανομή ηλεκτρονίων σε στιβάδες: K(2)-L(8)-M(8).</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να αντιστοιχίσετε τις στιβάδες της στήλης Α με το μέγιστο αριθμό ηλεκτρονίων που μπορούν να περιέχουν θεωρητικά στη στήλη Β.\\n\\nΣτήλη Α:\\n1. K\\n2. L\\n3. M\\n4. N\\n\\nΣτήλη Β:\\n1. 18\\n2. 8\\n3. 2\\n4. 32",
    a: "<span class='text-purple-300 font-bold'>Η σωστή αντιστοίχιση είναι:\\n1 - 3 (Στιβάδα K: 2 ηλεκτρόνια)\\n2 - 2 (Στιβάδα L: 8 ηλεκτρόνια)\\n3 - 1 (Στιβάδα M: 18 ηλεκτρόνια)\\n4 - 4 (Στιβάδα N: 32 ηλεκτρόνια)</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τον ακόλουθο πίνακα με τα δεδομένα της ηλεκτρονιακής κατανομής:<br><br><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Ιδιότητα / Στοιχείο</th><th>\\(^{80}_{35}\\text{Br}\\) (Βρώμιο)</th><th>\\(^{79}_{34}\\text{Se}\\) (Σελήνιο)</th><th>\\(^{31}_{15}\\text{P}\\) (Φωσφόρος)</th><th>\\(^{39}_{19}\\text{K}\\) (Κάλιο)</th><th>\\(^{2}_{1}\\text{H}\\) (Δευτέριο)</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός p</td><td></td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός n</td><td></td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός e</td><td></td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Κατανομή e σε στιβάδες</td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>",
    a: "<span class='text-purple-300 font-bold'><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Ιδιότητα / Στοιχείο</th><th>Βρώμιο</th><th>Σελήνιο</th><th>Φωσφόρος</th><th>Κάλιο</th><th>Δευτέριο</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός p</td><td>35</td><td>34</td><td>15</td><td>19</td><td>1</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός n</td><td>45</td><td>45</td><td>16</td><td>20</td><td>1</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός e</td><td>35</td><td>34</td><td>15</td><td>19</td><td>1</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Κατανομή e</td><td>K(2) L(8) M(18) N(7)</td><td>K(2) L(8) M(18) N(6)</td><td>K(2) L(8) M(5)</td><td>K(2) L(8) M(8) N(1)</td><td>K(1)</td></tr></tbody></table></span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τον ακόλουθο πίνακα κατανομής ηλεκτρονίων για τα ιόντα:<br><br><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Ιδιότητα / Ιόν</th><th>\\(^{24}_{12}\\text{Mg}^{2+}\\)</th><th>\\(^{32}_{16}\\text{S}^{2-}\\)</th><th>\\(^{19}_{9}\\text{F}^{-}\\)</th><th>\\(^{23}_{11}\\text{Na}^{+}\\)</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός p</td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός n</td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός e</td><td></td><td></td><td></td><td></td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Κατανομή e σε στιβάδες</td><td></td><td></td><td></td><td></td></tr></tbody></table>",
    a: "<span class='text-purple-300 font-bold'><table class='w-full text-center border-collapse my-4'><thead><tr class='border-b border-white/20'><th class='text-left py-2'>Ιδιότητα / Ιόν</th><th>Mg²⁺</th><th>S²⁻</th><th>F⁻</th><th>Na⁺</th></tr></thead><tbody><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός p</td><td>12</td><td>16</td><td>9</td><td>11</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός n</td><td>12</td><td>16</td><td>10</td><td>12</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Αριθμός e</td><td>10</td><td>18</td><td>10</td><td>10</td></tr><tr class='border-b border-white/10'><td class='text-left py-2'>Κατανομή e</td><td>K(2) L(8)</td><td>K(2) L(8) M(8)</td><td>K(2) L(8)</td><td>K(2) L(8)</td></tr></tbody></table></span>"
  },
  {
    chapterId: "chapter-2",
    q: "Ένα στοιχείο Χ έχει μαζικό αριθμό 14 και στον πυρήνα του ατόμου του έχει 2 νετρόνια περισσότερα από τα πρωτόνια του:\\nα. Να βρεθεί ο αριθμός πρωτονίων, νετρονίων και ηλεκτρονίων του ατόμου του στοιχείου Χ.\\nβ. Να γίνει η κατανομή των ηλεκτρονίων του ατόμου του στοιχείου Χ σε στιβάδες.\\nγ. Ένα άλλο άτομο (Ψ) έχει 6 πρωτόνια και 6 νετρόνια. Να χαρακτηρίσετε τις ακόλουθες προτάσεις ως σωστές ή λανθασμένες:\\n1. Τα δύο άτομα έχουν ίδιο μαζικό αριθμό.\\n2. Το άτομο αυτό είναι ισότοπο του Χ.\\n3. Το άτομο αυτό έχει διαφορετική μάζα από το άτομο που έχει μαζικό αριθμό 14.\\n4. Τα δύο άτομα έχουν διαφορετική ηλεκτρονιακή δομή.",
    a: "<span class='text-purple-300 font-bold'>α. Έχουμε A = 14 και n = p + 2. Ισχύει A = p + n ⇨ 14 = p + (p + 2) ⇨ 2p = 12 ⇨ p = 6. Άρα το στοιχείο Χ έχει p=6, n=8, e=6 (αφού είναι άτομο).<br>β. Η κατανομή είναι: K(2) L(4).<br>γ. 1. <b>Λάθος</b>. Το Ψ έχει A = 6+6=12, ενώ το Χ έχει A=14.<br>2. <b>Σωστό</b>. Το Ψ έχει 6 πρωτόνια, άρα Z=6, όπως και το Χ (Z=6). Εφόσον έχουν ίδιο Z και διαφορετικό A, είναι ισότοπα (Άνθρακας-12 και Άνθρακας-14).<br>3. <b>Σωστό</b>. Η μάζα του ατόμου που έχει μαζικό αριθμό 14 είναι μεγαλύτερη από τη μάζα του ατόμου που έχει μαζικό αριθμό 12.<br>4. <b>Λάθος</b>. Εφόσον και τα δύο άτομα έχουν τον ίδιο αριθμό ηλεκτρονίων (e=6), διαθέτουν ακριβώς την ίδια ηλεκτρονιακή δομή: K(2) L(4).</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Δίνονται τα άτομα: \\(^{39}_{19}\\text{K}\\) και \\(^{19}_{9}\\text{F}\\). Να βρεθούν:\\nα. Η σύσταση του πυρήνα τους.\\nβ. Η κατανομή των ηλεκτρονίων των ατόμων των δύο στοιχείων σε στιβάδες.\\nγ. Η κατανομή των ηλεκτρονίων των ιόντων \\(\\text{K}^{+}\\) και \\(\\text{F}^{-}\\) σε στιβάδες. Να αιτιολογήσετε τις απαντήσεις σας.",
    a: "<span class='text-purple-300 font-bold'>α. Για το \\(^{39}_{19}\\text{K}\\): Ο πυρήνας αποτελείται από 19 πρωτόνια και 39 - 19 = 20 νετρόνια.<br>Για το \\(^{19}_{9}\\text{F}\\): Ο πυρήνας αποτελείται από 9 πρωτόνια και 19 - 9 = 10 νετρόνια.<br>β. Η κατανομή των e⁻ για το K (19 e⁻) είναι: K(2) L(8) M(8) N(1).<br>Η κατανομή των e⁻ για το F (9 e⁻) είναι: K(2) L(7).<br>γ. Το ιόν \\(\\text{K}^{+}\\) προκύπτει με αποβολή 1 e⁻ (άρα 18 e⁻). Η κατανομή είναι: K(2) L(8) M(8).<br>Το ιόν \\(\\text{F}^{-}\\) προκύπτει με πρόσληψη 1 e⁻ (άρα 10 e⁻). Η κατανομή είναι: K(2) L(8).</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Ένα σωματίδιο έχει 20 πρωτόνια, 20 νετρόνια και 18 ηλεκτρόνια. Τι είδους σωματίδιο είναι αυτό: άτομο, ανιόν, κατιόν ή μόριο; Να γραφεί η κατανομή των ηλεκτρονίων του σε στιβάδες.",
    a: "<span class='text-purple-300 font-bold'>Εφόσον ο αριθμός των πρωτονίων (p=20) είναι κατά 2 μεγαλύτερος από τον αριθμό των ηλεκτρονίων (e=18), το σωματίδιο έχει πλεόνασμα θετικού φορτίου (+2). Επομένως, είναι ένα <b>κατιόν με φορτίο +2</b> (συγκεκριμένα το \\(\\text{Ca}^{2+}\\)).<br>Η κατανομή των 18 ηλεκτρονίων του σε στιβάδες είναι: K(2) L(8) M(8).</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να απαντήσετε στα παρακάτω ερωτήματα:\\nα. Τι είναι ο Περιοδικός Πίνακας;\\nβ. Σε ποιον νόμο στηρίζεται η ταξινόμηση των στοιχείων στον Περιοδικό Πίνακα;\\nγ. Να εξηγήσετε για ποιους λόγους είναι απαραίτητη η ταξινόμηση των χημικών στοιχείων.",
    a: "<span class='text-purple-300 font-bold'>α. Ο Περιοδικός Πίνακας είναι ένας πίνακας συστηματικής κατάταξης των χημικών στοιχείων κατά αύξοντα ατομικό αριθμό, έτσι ώστε στοιχεία με όμοιες ιδιότητες να βρίσκονται στην ίδια κατακόρυφη στήλη (ομάδα).<br>β. Η ταξινόμηση στηρίζεται στον νόμο της περιοδικότητας, ο οποίος αναφέρει ότι οι ιδιότητες των στοιχείων εμφανίζουν μια περιοδικότητα, δηλαδή επαναληψιμότητα έπειτα από συγκεκριμένο αριθμό στοιχείων.<br>γ. Μας επιτρέπει να οργανώσουμε και να κατανοήσουμε τα χημικά στοιχεία, να προσδιορίζουμε μοτίβα στη συμπεριφορά τους, να προβλέπουμε τις ιδιότητές τους και να τα αξιοποιούμε για την ανάπτυξη νέων υλικών.</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Ο ΟΗΕ σε συνεργασία με την IUPAC όρισαν το 2019 ως Διεθνές Έτος για τον Περιοδικό Πίνακα. Να διατυπώσετε τις σκέψεις σας για την αξία του περιοδικού πίνακα στην επιστήμη.",
    a: "<span class='text-purple-300 font-bold'>Ο Περιοδικός Πίνακας αποτελεί ένα από τα σημαντικότερα επιτεύγματα της επιστημονικής σκέψης. Οργανώνει τα χημικά στοιχεία με βάση τις ιδιότητές τους, αποτελεί βασικό εργαλείο στην εκπαίδευση παρέχοντας μια σαφή και συγκροτημένη εικόνα, επιτρέπει την πρόβλεψη της ύπαρξης νέων στοιχείων, και βοηθά στην ανάπτυξη νέων υλικών και τεχνολογιών που εφαρμόζονται στην καθημερινότητά μας.</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Να συμπληρώσετε τα κενά:\\nΤα στοιχεία στον σύγχρονο Περιοδικό Πίνακα είναι τοποθετημένα κατά αύξοντα ........ αριθμό με βάση τον νόμο της περιοδικότητας που προβλέπει ότι οι ........ των στοιχείων είναι ........ συνάρτηση του ........ τους αριθμού.",
    a: "<span class='text-purple-300 font-bold'>Τα στοιχεία στον σύγχρονο Περιοδικό Πίνακα είναι τοποθετημένα κατά αύξοντα <span class='text-white'>ατομικό</span> αριθμό με βάση τον νόμο της περιοδικότητας που προβλέπει ότι οι <span class='text-white'>ιδιότητες</span> των στοιχείων είναι <span class='text-white'>περιοδική</span> συνάρτηση του <span class='text-white'>ατομικού</span> τους αριθμού.</span>"
  },
  {
    chapterId: "chapter-2",
    q: "Ο Περιοδικός Πίνακας είναι ένα εξαιρετικά χρήσιμο εργαλείο γιατί βοηθά:\\nα. να οργανώσουμε, να μελετήσουμε και να κατανοήσουμε τα χημικά στοιχεία με βάση...\\nβ. να προβλέψουμε τις ιδιότητες στοιχείων και να...\\nγ. να κατανοήσουμε τη δομή της ύλης και...\\n(Ολοκληρώστε τις προτάσεις).",
    a: "<span class='text-purple-300 font-bold'>α. ...με βάση τις φυσικές και χημικές ιδιότητές τους.<br>β. ...να αξιοποιήσουμε τις προβλέψεις για την ανάπτυξη νέων υλικών.<br>γ. ...τις χημικές αντιδράσεις που πραγματοποιούνται όχι μόνο στο εργαστήριο, αλλά και στη φύση.</span>"
  }
];

let targetContent = fs.readFileSync('src/data/aLykeiouQuestions.ts', 'utf8');

const anchor = 'export const ch2Questions: Question[] = [';
const insertIdx = targetContent.indexOf(anchor) + anchor.length;

const stringified = missingQuestions.map(q => JSON.stringify(q, null, 2)).join(",\\n") + ",\\n";

targetContent = targetContent.substring(0, insertIdx) + "\\n" + stringified + targetContent.substring(insertIdx);

fs.writeFileSync('src/data/aLykeiouQuestions.ts', targetContent, 'utf8');
console.log('Successfully inserted ' + missingQuestions.length + ' missing questions into ch2Questions!');
